<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlogsSeeder extends Seeder
{
    public function run(): void
    {
        $blogs = [
            [
                'blog_title' => 'Why Wood Framing Remains the Backbone of American Construction',
                'slug' => 'why-wood-framing-remains-backbone-american-construction',
                'blog_summery' => 'Wood framing has been a cornerstone of construction in the United States for centuries. Despite advances in steel and concrete, wood continues to dominate residential and light commercial building. Here is why.',
                'blog_description' => '<h3>A Time-Tested Building Method</h3><p>Wood framing has been the go-to method for building homes and commercial structures in America for over 200 years. Its popularity is not by accident — wood offers a unique combination of strength, flexibility, affordability, and sustainability that few other materials can match.</p><p>At EM Building Contractors, LLC, we have built our reputation on delivering high-quality wood framing for projects across Texas. Our experienced carpenters understand the nuances of different wood species, load-bearing requirements, and local building codes.</p><h3>Key Advantages of Wood Framing</h3><ul><li><strong>Cost-Effective</strong> — Wood is generally less expensive than steel or concrete, making it the preferred choice for budget-conscious builders and homeowners.</li><li><strong>Speed of Construction</strong> — Wood frames can be erected quickly, reducing overall project timelines and labor costs.</li><li><strong>Energy Efficiency</strong> — Wood is a natural insulator, providing better thermal performance than steel framing. This translates to lower heating and cooling costs for building occupants.</li><li><strong>Design Flexibility</strong> — Wood is easy to cut, shape, and modify on-site, allowing for creative architectural designs and quick adjustments during construction.</li><li><strong>Sustainability</strong> — As a renewable resource, wood has a smaller carbon footprint compared to steel and concrete production. Sustainably harvested lumber is an environmentally responsible choice.</li></ul><h3>Modern Innovations in Wood Framing</h3><p>Today, wood framing has evolved with engineered lumber products like LVL beams, I-joists, and glue-laminated timber. These products offer greater strength and consistency than traditional dimensional lumber, enabling wood to be used in larger and more complex structures.</p><p>Cross-laminated timber (CLT) is another innovation pushing wood construction into new territory, with multi-story commercial and residential buildings now being constructed entirely from engineered wood products.</p><h3>Choosing the Right Framing Partner</h3><p>The quality of wood framing depends heavily on the skill and experience of the framing crew. Poorly framed walls lead to problems with drywall, flooring, roofing, and overall structural integrity. That is why it is critical to work with experienced professionals who understand proper nailing patterns, sheathing installation, and structural connections.</p><p>At EM Building Contractors, we ensure every frame we build is square, plumb, and level — giving your project the strongest possible foundation for everything that follows.</p>',
                'author' => 'EM Building Contractors',
            ],
            [
                'blog_title' => 'Metal Framing vs Wood Framing: Which is Right for Your Project?',
                'slug' => 'metal-framing-vs-wood-framing-which-is-right',
                'blog_summery' => 'Choosing between metal and wood framing is one of the most important decisions in construction. Each material has distinct advantages depending on your project type, budget, and building requirements.',
                'blog_description' => '<h3>Understanding the Differences</h3><p>Both metal (steel stud) and wood framing are widely used in construction, but they serve different purposes and perform differently in various applications. Understanding these differences will help you make the right choice for your project.</p><h3>When to Choose Wood Framing</h3><ul><li><strong>Residential construction</strong> — Single-family homes, duplexes, and townhomes are typically wood-framed due to cost and ease of construction.</li><li><strong>Budget-sensitive projects</strong> — Wood materials and labor generally cost less than steel alternatives.</li><li><strong>Projects requiring on-site modifications</strong> — Wood is easy to cut and adjust in the field.</li><li><strong>Areas with low moisture exposure</strong> — When properly treated and protected, wood performs well in controlled environments.</li></ul><h3>When to Choose Metal Framing</h3><ul><li><strong>Commercial buildings</strong> — Offices, retail spaces, hospitals, and schools often require the fire resistance and dimensional stability of steel.</li><li><strong>Multi-story construction</strong> — Steel framing provides consistent strength without the warping or shrinking issues that can affect wood over time.</li><li><strong>High-moisture environments</strong> — Steel does not rot, warp, or attract termites, making it ideal for coastal or humid climates.</li><li><strong>Fire-rated assemblies</strong> — Steel framing is non-combustible and is often required for fire-rated wall and ceiling assemblies in commercial construction.</li></ul><h3>Cost Comparison</h3><p>While steel studs themselves can be comparable in price to wood, the total installed cost of metal framing is typically higher due to specialized tools, fasteners, and the skill level required for installation. However, the long-term benefits of steel — including lower maintenance, pest resistance, and fire safety — can offset the initial cost difference in commercial applications.</p><h3>The EM Building Contractors Approach</h3><p>At EM Building Contractors, LLC, we are experienced in both wood and metal framing systems. We evaluate each project individually and recommend the framing method that best meets your structural requirements, budget, and timeline. Our crews are trained in both systems, ensuring consistent quality regardless of the material chosen.</p>',
                'author' => 'EM Building Contractors',
            ],
            [
                'blog_title' => 'The Complete Guide to Gypsum Concrete for Multi-Family Construction',
                'slug' => 'complete-guide-gypsum-concrete-multi-family-construction',
                'blog_summery' => 'Gypsum concrete underlayment is essential in multi-family and commercial construction for fire protection, sound control, and floor leveling. Learn everything you need to know about this specialized material.',
                'blog_description' => '<h3>What is Gypsum Concrete?</h3><p>Gypsum concrete is a mixture of gypsum plaster, portland cement, and sand that is pumped and poured over floor substrates to create a smooth, level surface. It is primarily used as an underlayment in multi-story buildings where fire ratings and sound attenuation between floors are critical requirements.</p><h3>Why Gypsum Concrete Matters in Multi-Family Projects</h3><p>Building codes for apartments, condominiums, and hotels require specific fire ratings and sound transmission ratings between dwelling units. Gypsum concrete plays a key role in meeting these requirements.</p><ul><li><strong>Fire Protection</strong> — Gypsum concrete is non-combustible and provides excellent fire ratings for floor-ceiling assemblies. It is a key component in many UL-listed fire-rated designs.</li><li><strong>Sound Control</strong> — A properly installed gypsum concrete underlayment significantly improves both STC (Sound Transmission Class) and IIC (Impact Insulation Class) ratings, reducing noise complaints between floors.</li><li><strong>Floor Leveling</strong> — Gypsum concrete is self-leveling, creating a perfectly flat surface for finished flooring materials like hardwood, tile, luxury vinyl, and carpet.</li><li><strong>Lightweight</strong> — At roughly half the weight of traditional concrete, gypsum concrete reduces the structural load on buildings, potentially allowing for lighter framing systems.</li></ul><h3>Installation Process</h3><p>Professional gypsum concrete installation involves several steps: substrate preparation, installation of sound mat or isolation membrane, placement of lath or reinforcement, and pumping of the gypsum concrete mixture. The material typically cures to walkable hardness within 90 minutes to 2 hours, and is ready for flooring installation within days rather than the weeks required for traditional concrete.</p><h3>Common Mistakes to Avoid</h3><ul><li>Insufficient substrate preparation leading to poor adhesion</li><li>Incorrect thickness that fails to meet fire rating requirements</li><li>Exposure to water or moisture before and after installation</li><li>Premature installation of finished flooring before adequate curing</li></ul><p>At EM Building Contractors, LLC, our gypsum concrete crews are trained and certified to deliver consistent, code-compliant installations on every project. We work closely with engineers and architects to ensure every pour meets the specified fire and acoustical ratings.</p>',
                'author' => 'EM Building Contractors',
            ],
            [
                'blog_title' => '5 Signs Your Commercial Roof Needs Immediate Attention',
                'slug' => '5-signs-commercial-roof-needs-immediate-attention',
                'blog_summery' => 'A failing commercial roof can lead to costly damage to your building and its contents. Here are five warning signs that your roof needs professional inspection and repair before a small problem becomes a major expense.',
                'blog_description' => '<h3>Do Not Ignore These Roof Warning Signs</h3><p>Your commercial roof is your building\'s first line of defense against the elements. In Texas, where severe storms, intense heat, and heavy rain are common, staying ahead of roof maintenance is critical to protecting your investment.</p><h3>1. Visible Ponding Water</h3><p>If you notice standing water on your flat roof more than 48 hours after a rain event, you have a drainage problem. Ponding water adds tremendous weight to the roof structure and accelerates deterioration of roofing membranes, leading to leaks and potential structural damage.</p><h3>2. Interior Water Stains or Leaks</h3><p>Water stains on ceiling tiles, damp spots on walls, or active dripping are obvious signs of a roof leak. Even small leaks can cause significant damage over time, including mold growth, damaged insulation, and compromised structural components.</p><h3>3. Blistering or Bubbling Membrane</h3><p>Blisters and bubbles in your roofing membrane indicate trapped moisture between layers. If left unaddressed, these blisters will eventually crack and expose the underlying roof structure to water infiltration.</p><h3>4. Damaged or Missing Flashing</h3><p>Flashing — the metal strips that seal joints, edges, and penetrations — is one of the most common failure points on commercial roofs. Loose, rusted, or missing flashing allows water to enter the building at these vulnerable transition points.</p><h3>5. Increased Energy Bills</h3><p>A sudden or gradual increase in heating or cooling costs can indicate that your roof insulation has become wet and lost its thermal performance. Compromised insulation not only raises energy costs but can also indicate ongoing moisture intrusion.</p><h3>What To Do Next</h3><p>If you notice any of these warning signs, schedule a professional roof inspection as soon as possible. Early detection and repair of roof problems is significantly less expensive than emergency repairs or full roof replacement.</p><p>EM Building Contractors, LLC provides comprehensive commercial roofing services including inspections, maintenance, repairs, and full replacements. Our experienced roofing team will assess your roof condition and recommend the most cost-effective solution to protect your building.</p>',
                'author' => 'EM Building Contractors',
            ],
            [
                'blog_title' => 'The Importance of Preventive Building Maintenance for Property Owners',
                'slug' => 'importance-preventive-building-maintenance-property-owners',
                'blog_summery' => 'Preventive maintenance is the most cost-effective way to protect your property investment. Regular inspections and proactive repairs prevent small issues from becoming expensive emergencies.',
                'blog_description' => '<h3>Why Preventive Maintenance Matters</h3><p>Every building — whether residential, commercial, or industrial — is subject to wear and tear from daily use, weather exposure, and the natural aging of materials. Without regular maintenance, minor issues like a small roof leak, a crack in the foundation, or a failing HVAC component can escalate into major problems that cost thousands of dollars to repair.</p><h3>The Real Cost of Deferred Maintenance</h3><p>Studies consistently show that deferred maintenance costs three to five times more than preventive maintenance. A small plumbing leak that costs a few hundred dollars to fix today could cause thousands in water damage, mold remediation, and drywall replacement if ignored for months.</p><p>Beyond direct repair costs, deferred maintenance leads to tenant dissatisfaction and turnover in commercial properties, reduced property values, code violations, and potential liability issues if unsafe conditions develop.</p><h3>What a Good Maintenance Program Includes</h3><ul><li><strong>Quarterly Inspections</strong> — Regular walk-throughs to identify developing issues before they become emergencies.</li><li><strong>Roof Maintenance</strong> — Annual inspections, gutter cleaning, and prompt repair of any damage.</li><li><strong>HVAC Servicing</strong> — Filter changes, system inspections, and preventive repairs to maintain efficiency and extend equipment life.</li><li><strong>Exterior Care</strong> — Pressure washing, painting, sealant renewal, and landscaping maintenance to protect the building envelope and curb appeal.</li><li><strong>Plumbing Checks</strong> — Inspection of fixtures, pipes, water heaters, and drainage systems to prevent leaks and water damage.</li><li><strong>Electrical Systems</strong> — Periodic inspection of panels, wiring, and fixtures to ensure safety and code compliance.</li></ul><h3>Partnering with the Right Maintenance Provider</h3><p>A good maintenance partner does not just respond to problems — they anticipate and prevent them. At EM Building Contractors, LLC, we create customized maintenance programs tailored to your property type, age, and specific needs. Our reliable teams handle everything from routine upkeep to emergency repairs, giving property owners peace of mind and protecting their investment for the long term.</p>',
                'author' => 'EM Building Contractors',
            ],
            [
                'blog_title' => 'Solar Energy for Commercial Buildings: What Property Owners Need to Know',
                'slug' => 'solar-energy-commercial-buildings-property-owners-guide',
                'blog_summery' => 'Commercial solar installations are booming across Texas. Learn about the benefits, costs, incentives, and practical considerations of adding solar energy to your commercial property.',
                'blog_description' => '<h3>The Solar Opportunity for Commercial Properties</h3><p>Texas ranks among the top states in the nation for solar energy potential, with abundant sunshine year-round. For commercial property owners, solar panels represent an opportunity to dramatically reduce operating costs while increasing property value and demonstrating environmental responsibility.</p><h3>Financial Benefits</h3><ul><li><strong>Reduced Electricity Bills</strong> — Commercial solar systems can offset 50 to 100 percent of a building\'s electricity consumption, depending on system size and energy usage patterns.</li><li><strong>Federal Tax Credit</strong> — The federal Investment Tax Credit (ITC) allows commercial property owners to deduct a significant percentage of the cost of solar installation from their federal taxes.</li><li><strong>Accelerated Depreciation</strong> — Commercial solar systems qualify for accelerated depreciation under MACRS, further reducing the effective cost of the system.</li><li><strong>Increased Property Value</strong> — Buildings with solar energy systems command higher sale prices and rental rates compared to similar properties without solar.</li></ul><h3>Practical Considerations</h3><p>Before investing in commercial solar, property owners should evaluate several factors including roof condition and age, available roof space and orientation, current electricity consumption and rates, local utility interconnection policies, and whether the roof structure can support the additional weight of solar panels.</p><h3>Roof-Ready Solar Installation</h3><p>One critical factor many property owners overlook is the condition of their existing roof. Installing solar panels on a roof that will need replacement within the next ten years is a costly mistake, as the panels must be removed and reinstalled during the roof replacement. We recommend completing any necessary roof repairs or replacement before solar installation.</p><h3>The EM Building Contractors Advantage</h3><p>As both a roofing contractor and solar installer, EM Building Contractors, LLC offers a unique advantage — we can assess your roof condition, complete any necessary repairs or replacement, and then install your solar system as a seamless, coordinated project. This integrated approach saves time, reduces costs, and ensures your roof and solar system work together for maximum performance and longevity.</p>',
                'author' => 'EM Building Contractors',
            ],
        ];

        foreach ($blogs as $blog) {
            $blog['blog_image'] = '';
            $blog['inner_image'] = null;
            $blog['active_flag'] = 1;
            $blog['created_at'] = now()->subDays(rand(1, 60));
            $blog['updated_at'] = now();
            DB::table('blogs')->insert($blog);
        }
    }
}
