<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServicesSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'service_title' => 'Wood Framing',
                'slug' => 'wood-framing',
                'service_summary' => 'Professional wood framing services for residential and commercial structures. We deliver precision-crafted frameworks that form the backbone of durable, long-lasting buildings.',
                'service_description' => '<h3>Expert Wood Framing Services</h3><p>At EM Building Contractors, LLC, our wood framing services are the foundation of quality construction. We specialize in building strong, precision-engineered wood frames for residential homes, commercial buildings, and custom structures throughout Texas.</p><h3>What We Offer</h3><ul><li><strong>Residential Framing</strong> – Complete framing for new homes, additions, and renovations including walls, floors, and roof systems.</li><li><strong>Commercial Framing</strong> – Large-scale wood framing for offices, retail spaces, and multi-unit developments.</li><li><strong>Custom Structures</strong> – Decks, pergolas, carports, and specialty wood structures built to your exact specifications.</li><li><strong>Load-Bearing Walls</strong> – Expert engineering and installation of structural walls that meet all building codes.</li></ul><h3>Why Choose Our Wood Framing?</h3><p>Our experienced carpenters use premium-grade lumber and follow strict structural engineering standards. Every frame we build is square, plumb, and level — ensuring your project starts on the strongest possible foundation. We work closely with architects, engineers, and project managers to deliver framing that meets timeline and budget requirements.</p><p>From single-family homes to large commercial projects, our team brings decades of combined experience to every job. We pride ourselves on clean job sites, efficient workflows, and craftsmanship you can see in every joint and connection.</p>',
            ],
            [
                'service_title' => 'Metal Framing & Drywall',
                'slug' => 'metal-framing-drywall',
                'service_summary' => 'Complete metal stud framing and drywall installation services. From commercial interiors to residential renovations, we deliver smooth, flawless finishes every time.',
                'service_description' => '<h3>Metal Framing & Drywall Installation</h3><p>EM Building Contractors, LLC provides comprehensive metal framing and drywall services for commercial and residential projects. Our skilled team handles everything from steel stud framing to finished drywall surfaces ready for paint.</p><h3>Our Services Include</h3><ul><li><strong>Metal Stud Framing</strong> – Lightweight steel framing for interior partitions, exterior walls, ceilings, and soffits. Ideal for commercial buildings, offices, and multi-story structures.</li><li><strong>Drywall Installation</strong> – Professional hanging, taping, mudding, and sanding of drywall sheets for smooth, paint-ready surfaces.</li><li><strong>Acoustical Ceilings</strong> – Drop ceiling and acoustical tile installation for commercial offices and retail spaces.</li><li><strong>Insulation</strong> – Thermal and sound insulation integrated with framing and drywall for energy efficiency and noise reduction.</li><li><strong>Fire-Rated Assemblies</strong> – Code-compliant fire-rated wall and ceiling assemblies for commercial and multi-family projects.</li></ul><h3>Why Metal Framing?</h3><p>Metal framing offers superior strength, fire resistance, and dimensional stability compared to traditional wood. It does not warp, shrink, or rot, making it the preferred choice for commercial construction. Our team is experienced in both load-bearing and non-load-bearing metal stud systems, ensuring your project meets all structural and code requirements.</p><p>We deliver clean, professional finishes on every drywall project — from Level 3 for texture finishes to Level 5 for high-end smooth walls. Our attention to detail ensures seamless joints and corners that stand up to the closest inspection.</p>',
            ],
            [
                'service_title' => 'Gypsum Concrete',
                'slug' => 'gypsum-concrete',
                'service_summary' => 'Specialized gypsum concrete underlayment services for floor systems. Lightweight, fire-resistant, and sound-dampening solutions for multi-story construction.',
                'service_description' => '<h3>Gypsum Concrete Underlayment Services</h3><p>EM Building Contractors, LLC offers professional gypsum concrete underlayment installation for multi-family, commercial, and hospitality projects. Gypsum concrete is the industry-standard solution for floor leveling, fire protection, and sound control in modern construction.</p><h3>Applications</h3><ul><li><strong>Multi-Family Housing</strong> – Apartments, condominiums, and townhomes requiring fire-rated floor-ceiling assemblies and sound attenuation.</li><li><strong>Commercial Buildings</strong> – Office complexes, hotels, and retail spaces needing level, durable floor substrates.</li><li><strong>Renovation Projects</strong> – Leveling uneven existing floors before installing finished flooring materials.</li></ul><h3>Benefits of Gypsum Concrete</h3><ul><li><strong>Lightweight</strong> – Significantly lighter than traditional concrete, reducing structural load on buildings.</li><li><strong>Fire Resistance</strong> – Provides excellent fire ratings for floor-ceiling assemblies, meeting UL design requirements.</li><li><strong>Sound Control</strong> – Superior STC and IIC ratings that minimize sound transmission between floors.</li><li><strong>Self-Leveling</strong> – Creates perfectly flat surfaces ideal for hardwood, tile, carpet, and vinyl flooring installation.</li><li><strong>Fast Curing</strong> – Walkable within hours and ready for flooring installation much faster than traditional concrete.</li></ul><p>Our crews are trained and certified in gypsum concrete application, using state-of-the-art pumping equipment to deliver consistent, high-quality pours on every project. We work with leading gypsum concrete manufacturers to ensure the best material performance for your specific application.</p>',
            ],
            [
                'service_title' => 'Roofing',
                'slug' => 'roofing',
                'service_summary' => 'Complete roofing services including installation, repair, and replacement for residential and commercial properties. Quality materials and expert workmanship guaranteed.',
                'service_description' => '<h3>Professional Roofing Services</h3><p>EM Building Contractors, LLC provides full-service roofing solutions for residential and commercial properties across Texas. Whether you need a new roof installation, repair, or complete replacement, our experienced roofing team delivers quality workmanship that protects your investment for decades.</p><h3>Our Roofing Services</h3><ul><li><strong>New Roof Installation</strong> – Complete roof systems for new construction projects, from sheathing to shingles or commercial membrane systems.</li><li><strong>Roof Replacement</strong> – Full tear-off and replacement of aging or storm-damaged roofs with modern, energy-efficient materials.</li><li><strong>Roof Repair</strong> – Leak detection and repair, flashing replacement, shingle repair, and emergency storm damage repairs.</li><li><strong>Commercial Roofing</strong> – Flat roof systems including TPO, EPDM, modified bitumen, and built-up roofing for commercial buildings.</li><li><strong>Residential Roofing</strong> – Asphalt shingles, architectural shingles, metal roofing, and tile roofing for homes.</li></ul><h3>Why Our Roofing Stands Out</h3><p>We use only premium roofing materials from trusted manufacturers and back our work with comprehensive warranties. Our roofing crews follow strict safety protocols and maintain clean, organized job sites throughout the project. From the initial inspection to final cleanup, we ensure a smooth, stress-free roofing experience.</p><p>Every roof we install is built to withstand the Texas climate — from intense summer heat to severe storm conditions. We also assist with insurance claims for storm-damaged roofs, making the restoration process as easy as possible for property owners.</p>',
            ],
            [
                'service_title' => 'Building Maintenance',
                'slug' => 'building-maintenance',
                'service_summary' => 'Comprehensive building maintenance services to keep your property in top condition. Preventive maintenance, repairs, and facility management for commercial and residential buildings.',
                'service_description' => '<h3>Building Maintenance Services</h3><p>EM Building Contractors, LLC offers reliable building maintenance services designed to protect your property value and ensure safe, comfortable environments for occupants. Our maintenance programs cover everything from routine inspections to emergency repairs.</p><h3>What We Cover</h3><ul><li><strong>Preventive Maintenance</strong> – Scheduled inspections and maintenance to identify and fix issues before they become costly problems.</li><li><strong>General Repairs</strong> – Drywall repair, painting, plumbing fixes, electrical troubleshooting, door and window repairs, and general handyman services.</li><li><strong>Exterior Maintenance</strong> – Siding repair, pressure washing, gutter cleaning, parking lot maintenance, and exterior painting.</li><li><strong>HVAC Support</strong> – Filter changes, duct cleaning coordination, and HVAC system maintenance scheduling.</li><li><strong>Emergency Services</strong> – 24/7 emergency response for water damage, storm damage, fire damage, and other urgent building issues.</li><li><strong>Tenant Improvements</strong> – Buildout and renovation of commercial spaces for new tenants, including walls, flooring, lighting, and finishes.</li></ul><h3>Tailored Maintenance Programs</h3><p>We understand that every building has unique maintenance needs. That is why we create customized maintenance plans based on your property type, age, usage, and budget. Our dedicated maintenance teams are reliable, professional, and committed to keeping your building in peak condition year-round.</p><p>Whether you manage a single commercial property or a portfolio of buildings, EM Building Contractors provides the consistent, high-quality maintenance services you can count on.</p>',
            ],
            [
                'service_title' => 'Concrete',
                'slug' => 'concrete',
                'service_summary' => 'Professional concrete services for foundations, slabs, driveways, sidewalks, and structural elements. Precision pouring and finishing for lasting results.',
                'service_description' => '<h3>Concrete Construction Services</h3><p>EM Building Contractors, LLC delivers professional concrete services for residential, commercial, and industrial projects. From foundations to decorative flatwork, our concrete crews bring precision and expertise to every pour.</p><h3>Our Concrete Services</h3><ul><li><strong>Foundations</strong> – Slab-on-grade foundations, pier and beam foundations, and commercial post-tension foundations engineered for Texas soil conditions.</li><li><strong>Flatwork</strong> – Driveways, sidewalks, patios, garage floors, and parking lots with proper grading and drainage.</li><li><strong>Structural Concrete</strong> – Retaining walls, columns, beams, elevated slabs, and other structural elements.</li><li><strong>Concrete Repair</strong> – Crack repair, resurfacing, leveling, and restoration of existing concrete structures.</li><li><strong>Decorative Concrete</strong> – Stamped, stained, and polished concrete finishes for aesthetic applications.</li><li><strong>Site Work</strong> – Grading, excavation, compaction, and preparation of subgrade prior to concrete placement.</li></ul><h3>Quality You Can Build On</h3><p>We use high-quality concrete mixes specified for each application, with proper reinforcement including rebar, wire mesh, and fiber as required by engineering specifications. Our finishing crews deliver smooth, level surfaces with proper control joints and edge details.</p><p>Every concrete project starts with thorough site preparation and formwork, ensuring accurate dimensions and proper drainage. We monitor weather conditions and curing processes to achieve optimal concrete strength and durability. From small residential pours to large commercial foundations, EM Building Contractors delivers concrete work that stands the test of time.</p>',
            ],
            [
                'service_title' => 'Solar Solutions',
                'slug' => 'solar-solutions',
                'service_summary' => 'Sustainable solar energy solutions for residential and commercial properties. Reduce energy costs and your carbon footprint with our professional solar panel installation services.',
                'service_description' => '<h3>Solar Energy Solutions</h3><p>EM Building Contractors, LLC is committed to sustainable construction and offers comprehensive solar energy solutions for residential and commercial properties. We help property owners harness the power of the sun to reduce energy costs, increase property value, and contribute to a cleaner environment.</p><h3>Our Solar Services</h3><ul><li><strong>Solar Panel Installation</strong> – Professional installation of rooftop and ground-mounted solar photovoltaic systems for homes and businesses.</li><li><strong>Commercial Solar</strong> – Large-scale solar installations for offices, warehouses, retail centers, and industrial facilities.</li><li><strong>Solar Carports</strong> – Dual-purpose structures that provide vehicle shade while generating clean energy.</li><li><strong>System Design</strong> – Custom solar system design based on your energy consumption, roof orientation, and budget goals.</li><li><strong>Maintenance & Monitoring</strong> – Ongoing system monitoring, cleaning, and maintenance to ensure optimal energy production.</li><li><strong>Battery Storage</strong> – Integration of battery storage systems for energy independence and backup power during outages.</li></ul><h3>Why Go Solar?</h3><ul><li><strong>Reduce Energy Bills</strong> – Solar panels can significantly lower your monthly electricity costs, with many systems paying for themselves within a few years.</li><li><strong>Tax Incentives</strong> – Take advantage of federal and state tax credits, rebates, and incentives available for solar installations.</li><li><strong>Increase Property Value</strong> – Properties with solar systems typically see an increase in market value.</li><li><strong>Environmental Impact</strong> – Reduce your carbon footprint and contribute to cleaner air and a sustainable future.</li></ul><p>Our solar team handles everything from initial energy assessment and system design to permitting, installation, and utility interconnection. We partner with leading solar equipment manufacturers to provide high-efficiency panels, inverters, and mounting systems backed by industry-leading warranties.</p>',
            ],
        ];

        foreach ($services as $service) {
            $service['service_image'] = '';
            $service['inner_image'] = null;
            $service['type'] = 'service';
            $service['active_flag'] = 1;
            $service['created_at'] = now();
            $service['updated_at'] = now();
            DB::table('services')->insert($service);
        }
    }
}
